### ISSUE TITLE
buildtestファームでは右側のLEDのラスト6個が点かないことがある

### ISSUE THREAD

**Issue by koron** [hanachi-ap/willow64-doc#10]
biuldtestファームを使っていると、選択される点灯パターン(例:数秒ごとにR→G→Bと色が変換するやつ等)によっては、右側をUSBに直接接続(master)にした際に最後の5個、すなわち58～63番のLEDが点灯しません。そのためLEDを正しく接続できていてもできていないと勘違いしてしまうことがあります。

なおこの場合でもslaveとして繋ぐ≒左側をUSBに繋ぎ右側はTRRSケーブルでつなげば全灯点灯します。

ご存じの通りRGB LEDは信号線上に1個目からn個目までの点灯データを流しています。masterの左側は29個のLEDがあるのに、右側が35個であることからこの差の分のLEDが点灯していないのだと推測されます。

この挙動は組み立て時テスト用のファームとしてはふさわしくありません。必ず特定のパターンを再生し、加えてパターンはmasterのLEDデータを参照しないものを選ぶべきです。

---

以下ざっくり経緯を。

初回まっさらなPicoMicroにビルドテストファームを焼いたときはRGB Swarmあたりのアニメーションパターンが再生され、それでは右側masterでも58～63番は点灯しました。

しかし一度デフォルトファームを焼いていろいろやってから、再びビルドテストファームを焼いた際にはRGBの切り替わりテストパターンになり、58～63番が点灯しなくなりました。(私はコレを壊したと勘違いしてLEDの交換作業でスったもんだした)

おそらくEEPROMを見てテストパターンを決めているのでしょう。で、このRGBテストパターンはmasterのLEDデータを見てその数29個分しか点灯データを送らないと推測されます。しかし右側には35個のLEDがありますから最後の6つ58～63番が点灯しません。

**Comment by hanachi-ap** [comment]
報告の問題点について理解しました。無駄たお手数をおかけしてしまってすいません

テスト用に、左右別々のhexを用意する形で修正します。
(キーコードにつては同様の問題を認知し修正していましたが、LEDは横並び確認漏れ、というやつです)

> 初回まっさらなPicoMicroにビルドテストファームを焼いたときはRGB Swarmあたりのアニメーションパターンが再生され

実はこちらのほうが原因がわかっていません。初期化コードで    rgblight_mode(RGBLIGHT_MODE_RGB_TEST);
を入れているので。時々VAIが予期せぬ副作用を起こす時があるのでdefault keymapがはじめからVIA対応というのも含め見直してみます。

**Comment by hanachi-ap** [comment]
暫定対処として少し強引なソース修正で解消しました。

Releaseフォルダにはコンパイル済みファームを置き換えしてあります。

**Comment by koron** [comment]
> Releaseフォルダにはコンパイル済みファームを置き換えしてあります。

Release フォルダというのは https://github.com/hanachi-ap/qmk_firmware/releases/tag/rev02-1 これであっていますでしょうか?

> > 初回まっさらなPicoMicroにビルドテストファームを焼いたときはRGB Swarmあたりのアニメーションパターンが再生され
> 
> 実はこちらのほうが原因がわかっていません

https://github.com/hanachi-ap/qmk_firmware/blob/ac15e9d8b8ed198613af6f02dc8660be5e4d41e9/keyboards/willow64/rev2/keymaps/hanachi_custom/keymap.c#L131

```c
void keyboard_post_init_user(void) {
    rgblight_layers = rgb_layers;
    rgblight_enable_noeeprom();
    rgblight_mode(RGBLIGHT_MODE_RAINBOW_SWIRL);
```

これじゃないですかね? なんか僕が忘れてる手順があってこのアニメーション設定がEEPROMに書き込まれてて…みたいな。

**Comment by koron** [comment]
> Release フォルダというのは https://github.com/hanachi-ap/qmk_firmware/releases/tag/rev02-1 これであっていますでしょうか?

ここに置いてあった buildtest を右側に書き込んでマスターにして起動したところ、すべてのLEDが点灯し正しく動作することを確認しました。

ありがとうございます!
