### ISSUE TITLE
ゴム足の取り付け位置の推奨箇所の提示が欲しい

### ISSUE THREAD

**Issue by koron** [hanachi-ap/willow64-doc#11]
ビルドガイドには以下のように書いてありゴム足の位置がわかる以下の写真が含まれていますが
確認できるゴム足は3つだけで4つ目の取り付け位置がわかりません。

> ゴム足を4箇所に貼り付けます。

試しにProMicro周辺に付けると若干浮く感じになるので、取り付け場所に指針が欲しいです。
なお私は[特殊なテープ](https://www.amazon.co.jp/gp/product/B07YF9L85P/)をゴム足とカバーの間に挟んで
厚みと柔らかさを稼いでます。

![](https://raw.githubusercontent.com/hanachi-ap/willow64-doc/main/img/img11.jpg)

**Comment by hanachi-ap** [comment]
ご提案ありがとうございます。
現在次のリビジョンの制作を行っています。ボトムプレートの形状も若干変わる予定なので、次のドキュメント改版のなかで吸収することを予定します。

備考: 製品添付のゴム足は必要最低限のものになっていますが、製作者としてはチルト/テント角をつけることでより操作性が高まると考えています。このあたりは利用者の嗜好も合わせてTIPSを盛り込もうと思います。
