### ISSUE TITLE
Additional resources

### ISSUE THREAD

**Issue by azzamsa** [hanachi-ap/willow64-doc#13]
Hi.

I really love this new innovative layout.
But, since this is extremely fresh.
I would like to see someone typing on it in the video.

I love to see where it goes. But sadly I can't find any resources.
Only 2 announcements in the Reddit post and the introductory post by the author.

Any additional resource would be fun.

Thank you

**Comment by hanachi-ap** [comment]
hi.
Thank you for your interest in Willow.

I just heard that we are planning to release a review video by users soon.
I'll introduce it when it's released.

**Comment by azzamsa** [comment]
Thanks I a lot.

I have also [requested a review](https://www.youtube.com/watch?v=bcR5LKi4U7c&lc=UgxADPc-HDFaLkFkEU14AaABAg) from Japanese blogger Daihuku Keyboard.

He replied, It will be released tomorrow. Can't wait to see :)


![image](https://user-images.githubusercontent.com/17734314/110960275-2897f800-8381-11eb-9285-4273ffbcd767.png)

**Comment by azzamsa** [comment]
Thankfully it is on air [now](https://m.youtube.com/watch?v=uEMPQG3C1HY)

Would you like to add the layout to https://github.com/jhelvy/splitKbCompare?
So we can compare, print and try it on paper.
