### ISSUE TITLE
入らないTRRSケーブルの詳細

### ISSUE THREAD

**Issue by koron** [hanachi-ap/willow64-doc#3]
https://twitter.com/haswellep/status/1343220957465387009

> これは設計を見直さなきゃいけない範囲なので～ちなみにケーブル側の直径わかりますか

次の写真のケーブルです。計測は写真内のシンワのノギスです。

位置 | 入手元 | 挿入可否 | 直径 | 備考
---|---|---|---|---
左上 | [遊舎工房](https://yushakobo.jp/shop/trrs_cable/) |  可 | 6.0mm |
右上 | [Amazon](https://www.amazon.co.jp/gp/product/B01MXCKHAM/) | 条件次第で可 | 7.2mm/8.7ｍｍ | 円形ではない。短辺を少し削るように入る
左下 | [Amazon](https://www.amazon.co.jp/gp/product/B07SL84NM2/) | 不可 | 9.0±0.1mm | 
右下 | [Amazon](https://www.amazon.co.jp/gp/product/B07G1VGY29/) | 不可 | 8.8mm |

![image](https://user-images.githubusercontent.com/468368/103175074-ac763400-48aa-11eb-9f34-808c0c292ffa.png)

**Comment by hanachi-ap** [comment]
カバープレートとTRRSケーブルが干渉する問題点を確認しました。
確認時のケーブルのサンプル不足でした。頂いた情報は非常に参考になります。
本件についてはPCB及びプレート両面での対処が必要となるため、時期リビジョンにて対応を検討します。

**Comment by koron** [comment]
現状でもこういうの買えば好きなケーブルが付けられそうです。

っていうか買ったので後日レポートしますw

https://www.amazon.co.jp/dp/B016AHYRNW/

**Comment by koron** [comment]
↑の商品、完璧でした。以下のように、コネクタを延伸してどんなケーブルでも繋がります。

![image](https://user-images.githubusercontent.com/468368/103327916-0426c200-4a9a-11eb-9665-6a0514883e29.png)

これを使った状態で全キーが機能するところまで確認しました。

![image](https://user-images.githubusercontent.com/468368/103328178-105f4f00-4a9b-11eb-85ca-eb46ed8b15bc.png)

ぶっちゃけコレを前提にするとデザインの幅が広がるかもしれませんねw
