### ISSUE TITLE
右側のスタビライザを付けないように案内する

### ISSUE THREAD

**Issue by koron** [hanachi-ap/willow64-doc#4]
右側のスタビライザのキースイッチがスタビライザの中心にありません。
そのためスタビライザーを付けてしまうと
2u(以上の)キーキャップが取り付けられないか
無理矢理取り付けた場合はキーキャップの動作が不安定になります。
取り急ぎビルドガイドなどで
右側のスタビライザーを付けないように
案内したほうが良いかと思います。

---

以下、写真で。

スタビライザーの軸に合わせると、キースイッチの軸が若干左に寄っている。
![image](https://user-images.githubusercontent.com/468368/103175892-ef3b0a80-48b0-11eb-8e5c-2cddb84e87ef.png)

キースイッチの左の隙間が右よりも明らかに狭い。
![image](https://user-images.githubusercontent.com/468368/103175908-109bf680-48b1-11eb-8a0d-f07cbb6c7413.png)

シルク印刷も左に寄っている。
![image](https://user-images.githubusercontent.com/468368/103175918-26a9b700-48b1-11eb-8e6e-d9f514d63aa5.png)

装着しているスタビライザーは遊舎工房で購入した [MXスイッチ スタビライザー](https://yushakobo.jp/shop/a0500st/) の黒、2Ux1 です。

**Comment by hanachi-ap** [comment]
報告頂いた問題を確認しました。

手元のスタビライザとキーキャップの組み合わせでは大きな違和感を感じていなかったための見逃しです。

PCBの修正が必要なため時期リビジョンでのしゅうせいを検討します。
暫定対処として現行バージョンでの制限事項をドキュメント化します。
