### ISSUE TITLE
PCBにあるキースイッチの補助足用の穴の間隔が狭い

### ISSUE THREAD

**Issue by koron** [hanachi-ap/willow64-doc#5]
PCBマウント5ピンの仕様のキースイッチを使うと補助足用の穴の間隔が若干狭くて正常には取り付けられません。そのためPCBとトッププレートの間に力がかかりキースイッチが抜けやすくなります。(次の写真を参照) 

![image](https://user-images.githubusercontent.com/468368/103187691-b169d080-4908-11eb-9d2d-32b9bdd040fe.png)

加えてこのように取り付けてしまうと次の写真のようにキースイッチの補助足を削ることになってしまいます。(左側のスイッチの右側の足が削れている。右側はPCBに差してない正常なもの)

![image](https://user-images.githubusercontent.com/468368/103187593-44563b00-4908-11eb-9a55-5fbf29e28d24.png)

写真のキースイッチは [Gateron Silentスイッチ](https://yushakobo.jp/shop/a02gs/) です。このスイッチで補助足と主足との隙間を計測したら 2.3mm でした。一方でPCBのほうは 2.1～2.2mm でした。

参考までにCorne Cherry v3での設置状況も共有します。こちらは [Gateronスイッチ](https://yushakobo.jp/shop/a0200ga/) ですが、PCBとスイッチのハウジングに隙間はなく、補助足の先端がPCBよりも下に出ているのが見てとれます。

![image](https://user-images.githubusercontent.com/468368/103187901-9c417180-4909-11eb-9f2d-01144f0e8967.png)

**Comment by koron** [comment]
書き忘れ。対象のPCBは左右両方です。後程、ちょっと穴を削って広げてどうなるかやってみます。

**Comment by koron** [comment]
[ヤスリ](https://www.hobby-wave.com/products/ht424/) で削ってみました。両穴の外側と下側を10コスりくらい、右側の内側を数コスり。写真のSW-L22が削り済みでスムーズに入るようになります。SW-L26は削っていないので比較対象に。

![image](https://user-images.githubusercontent.com/468368/103189637-f3971000-4910-11eb-89b2-3b5456f725ba.png)

**Comment by hanachi-ap** [comment]
報告いただいた問題について承知しました。
足が削れるほどの干渉は確認できていなかったため手持ちのスイッチで現在再現性を確認しています。

基本、キーボード設計のオーソドックスなフットプリントライブラリを使用しているため、フットプリントパーツの選定ミス(もともとキツキツを前提にしていたもの??)か、PCB製造時の誤差? など調査から入ります。

**Comment by koron** [comment]
PCBの製造誤差、もしくは機械特性の可能性が高そうです。

というのも右側のLED窓についても次の写真で示すようにカットの精度が悪く、角が出ていない&削り溝が残っており SK6812MINI-Eが入らなかったので削りました。写真は SW-R20 のものですが、右側に関しては全部の窓を削る必要がありました。左側はそのような必要はありませんでした。

![image](https://user-images.githubusercontent.com/468368/103189833-e890af80-4911-11eb-801c-9af2a5f95e61.png)

**Comment by hanachi-ap** [comment]
LEDのホールの件もご報告ありがとうございます。
いま手元にあるPCBでもRが見てわかるほどの削り残しは見えないので製造時の差が大きいようです。

同じ設計でも製造メーカごとに差がでるのでいい感じになるメーカーを見つけるのも大事、という先達のノウハウもありますので検討します。
ただ、たしかにスイッチの足はキツめなのでフットプリントについても見直しを行いたいと思います。

**Comment by hanachi-ap** [comment]
Cherry MKの規格では 補助足の直径 1.7018mm±0.0508mm (  0.067inch±0.002)となっています。
(https://datasheet.octopart.com/MX1A-11NW-Cherry-datasheet-34676.pdf)

課題となっているrev2.0のPCBのフットプリントは 設計時1.70mmとしています。
手元の現物はおおよそ1.65~1.71程度(任意サンプリング)でしたのでとほぼ公差の範囲には入っているかとおもいます。
しかし実際には私の手持ちのスイッチでも非常にきついものがあることを確認しました。

補助時足はPCBにスイッチを固定するためのものとして考慮されているので妥当なのかもしれませんが、プレートを使用する際はマイナス効果が大きいため次のリビジョンではホールサイズを大きくするようにします。(具体的には0.175を予定)

**Comment by hanachi-ap** [comment]
ビルドガイドは次のリビジョンに向けての見直しの中で吸収しますが、個別のリビジョンに対する注意事項は本文の中でなく注意事項として外部で注釈するようにしたいと思います。

**Comment by koron** [comment]
穴の直径ではなく位置関係(=距離)の可能性はないでしょうか。
私の観測範囲だと両穴を外側に削ることで入るようになりました。

公差範囲内のものが3つ(中央の大足x1+小足2本)が組み合わさって
最終的に交差の範囲を超えた、みたいなことを想定しています。
