### ISSUE TITLE
ケースの組み立て手順の修正提案

### ISSUE THREAD

**Issue by koron** [hanachi-ap/willow64-doc#9]
[ビルドガイド](https://github.com/hanachi-ap/willow64-doc/blob/main/buildguide-willow64-r2.md#11%E3%82%B1%E3%83%BC%E3%82%B9%E3%81%AE%E7%B5%84%E3%81%BF%E7%AB%8B%E3%81%A6) に書かれた手順で組み立てると #6 のようなトラブルにあうことが考えられます。それを避けるためにケース組み立ての手順を修正したほうが良いでしょう。

たとえば [Corne Cherry](https://github.com/foostan/crkbd/blob/master/corne-cherry/doc/v3/buildguide_jp.md#%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%B9%E3%82%A4%E3%83%83%E3%83%81) だとトッププレートにスイッチを付けてからPCBに装着することを推奨しています。

> トッププレートにキースイッチに取り付けた後、キースイッチをソケットにはめ込みます。 先にすべてのキースイッチをトッププレートに取り付けてしまうと、ソケットにはめ込む難易度が上がってしまうため、先に端のキースイッチのみを取り付ける方が簡単です。

---

以下、組み立て手順の修正案

1. トッププレートとPCBを4個のスペーサーSと8個のネジSで接続する。この時ネジは緩め(抵抗を感じる程度から半回転ほど戻す程度)にする。
2. トッププレートのネジの近くの4か所にキースイッチを装着することで、トッププレートとPCBの位置を合わせをする。
3. トッププレートとPCBを繋ぐ8個のネジSを締める。
4. トッププレートに8個のスペーサーLを8個のネジSで接続する。この時ネジは緩め(抵抗を感じる程度から半回転ほど戻す程度)にする。
5. ボトムプレートを4つのネジLで手順4のスペーサのうち4つに固定する。この時ネジは緩め(抵抗を感じる程度から半回転ほど戻す程度)にする。
6. アンダーカバープレートを4つのネジLで接続する。
7. トッププレートとボトムプレートの緩めに装着したネジを適度に締める。

**Comment by koron** [comment]
@hanachi-ap こんな感じに直してよければ、後日になりますがPRを出しますけどどうでしょうか?

**Comment by hanachi-ap** [comment]
そんなに甘えるのも恐縮ですが、、もしよろしければお願いします

**Comment by hanachi-ap** [comment]
PRの内容を確認しました。次のリビジョン向けの修正に取り込む予定です。
